[package]
name = "Cryptor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
aes = "0.8.2"
clap = "4.1.8"
env_logger = "0.10.0"
